from app.models import ContentFormat, Subject

TOPICS = [
    {
        "title": "Nerve Injuries with Fractures — Lower Limb",
        "subject": Subject.orthopedics,
        "content_format": ContentFormat.rapid_revision,
        "poster_text": "Nerve Injuries in Lower Limb Fractures — Know Your Anatomy Cold",
        "caption": "NERVE INJURIES WITH LOWER LIMB FRACTURES\n\nMastering nerve-fracture associations is essential for NEET-PG/INI-CET. These are high-yield one-liners that appear almost every exam cycle.\n\nFEMUR & HIP:\n• Posterior hip dislocation → Sciatic nerve injury (especially common peroneal division)\n• Acetabular fracture → Obturator nerve injury\n• Femoral neck/shaft fracture → Femoral nerve (rare, but tested)\n\nKNEE REGION:\n• Fibular head fracture / knee dislocation → Common peroneal nerve → Foot drop (loss of dorsiflexion + eversion)\n• Knee dislocation → Popliteal artery injury (check pulses immediately)\n\nANKLE & FOOT:\n• Medial malleolus fracture → Tibial nerve injury → Loss of plantar flexion + inversion\n• Calcaneal fractures → Lateral plantar nerve\n\nCOMMON PERONEAL NERVE PALSY:\n• Foot drop = inability to dorsiflex\n• Steppage gait (high-stepping to clear the foot)\n• Loss of sensation over dorsum of foot and first web space\n• Tested with: Lateral fibular neck fracture scenario\n\nSCIATIC NERVE INJURY:\n• Combined features: foot drop + loss of plantar flexion\n• Loss of sensation below knee (all territories)\n• Always check for sciatic nerve in posterior hip dislocation\n\nHIGH-YIELD MNEMONIC: \"POP GOES THE PERONEAL\" — Posterior hip dislocation → sciatic, Fibular nOse → Peroneal",
        "high_yield_takeaway": "Posterior hip dislocation → sciatic nerve; fibular neck fracture → common peroneal nerve (foot drop). These two are the most tested associations.",
        "hashtags": ["#MedicoHelp", "#MBBS", "#NEETPG", "#Orthopedics", "#NerveInjury"],
    },
    {
        "title": "Compartment Syndrome — Diagnosis and Emergency Management",
        "subject": Subject.orthopedics,
        "content_format": ContentFormat.rapid_revision,
        "poster_text": "Compartment Syndrome — The 6 P's That Save Limbs",
        "caption": "COMPARTMENT SYNDROME — RAPID REVISION\n\nAcute compartment syndrome is a surgical emergency. Know it cold — both for exams and clinical practice.\n\nDEFINITION:\nRise in intracompartmental pressure (>30 mmHg or within 30 mmHg of diastolic) compromising perfusion → ischemia → necrosis if untreated.\n\nCOMMON CAUSES:\n• Fractures (especially tibia — most common site overall)\n• Tight casts / circumferential bandages\n• Crush injuries, Burns, Reperfusion injury\n• Supracondylar fracture of humerus (children — most common upper limb cause)\n\nCLINICAL FEATURES — THE 6 P's:\n1. Pain — out of proportion to injury; worsened by passive stretch (MOST IMPORTANT early sign)\n2. Pressure — tense/woody compartment on palpation\n3. Paresthesia — tingling; early nerve ischemia\n4. Paralysis — late sign; nerve/muscle necrosis\n5. Pallor — vascular compromise\n6. Pulselessness — VERY LATE sign (limb loss imminent)\n\nDIAGNOSIS:\n• Clinical diagnosis primarily\n• Compartment pressure measurement: Stryker device\n• Threshold for fasciotomy: pressure >30 mmHg OR delta pressure (diastolic − compartment pressure) <30 mmHg\n\nTREATMENT:\n• Remove all constricting bandages immediately\n• Emergency fasciotomy — do NOT delay\n• Tibia: 4-compartment fasciotomy (anteromedial + posterolateral incisions)\n• Forearm: Henry's approach + medial\n\nSEQUELAE if missed:\n• Volkmann's ischemic contracture (forearm/hand)\n• Myoglobinuria → acute renal failure\n• Permanent neurological deficit",
        "high_yield_takeaway": "Pain on passive stretch is the earliest and most important sign. Fasciotomy is indicated when compartment pressure >30 mmHg or delta pressure <30 mmHg.",
        "hashtags": ["#MedicoHelp", "#MBBS", "#NEETPG", "#Orthopedics", "#CompartmentSyndrome"],
    },
    {
        "title": "Salter-Harris Fracture Classification — MCQ",
        "subject": Subject.orthopedics,
        "content_format": ContentFormat.mcq,
        "poster_text": "Salter-Harris Fractures — Which Type Has the Worst Prognosis?",
        "caption": "SALTER-HARRIS FRACTURE CLASSIFICATION\n\nThese physeal fractures occur in children and are frequently tested. The classification determines prognosis and management.\n\nTYPES (mnemonic: SALTR):\n• Type I — Slip: Fracture through physis only. Best prognosis. X-ray may be normal.\n• Type II — Above: Through physis + metaphysis. MOST COMMON (75%). Good prognosis.\n• Type III — Lower/Below: Through physis + epiphysis into joint. Intra-articular. Moderate prognosis.\n• Type IV — Through: Through metaphysis + physis + epiphysis. Needs ORIF. Worse prognosis.\n• Type V — Rammed/Crush: Crush injury of physis. Worst prognosis. X-ray may appear normal.\n\nHIGH-YIELD POINTS:\n• Type II is most common\n• Types I and II: generally managed conservatively\n• Types III, IV: require anatomic reduction (ORIF) due to intra-articular involvement\n• Type V: retrospective diagnosis; worst growth disturbance\n• Growth arrest / limb length discrepancy is the feared complication",
        "question": "A 9-year-old boy falls from a bicycle and injures his right ankle. X-ray shows a fracture line passing through the growth plate and extending into the epiphysis, with an intra-articular component. There is no involvement of the metaphysis. Which Salter-Harris type is this, and what is the recommended management?",
        "options": [
            "A. Type II — closed reduction and casting",
            "B. Type III — open reduction and internal fixation",
            "C. Type IV — closed reduction and casting",
            "D. Type V — observation and non-weight bearing",
        ],
        "correct_answer": "B. Type III — open reduction and internal fixation",
        "explanation": "The fracture described involves the physis (growth plate) and extends into the epiphysis with intra-articular involvement but does NOT cross the metaphysis — this is the classic description of a Salter-Harris Type III fracture. Type III fractures are intra-articular and risk both growth disturbance and joint incongruity. Anatomic reduction is essential to restore joint surface and minimize growth arrest, making open reduction and internal fixation (ORIF) the treatment of choice. Type II involves the metaphysis (not described here). Type IV passes through metaphysis, physis, AND epiphysis. Type V is a crush injury of the physis — often diagnosed retrospectively. Remember: Types III and IV require ORIF; Types I and II are managed conservatively in most cases.",
        "high_yield_takeaway": "Salter-Harris Type II is most common (best prognosis). Type III/IV are intra-articular → need ORIF. Type V has worst prognosis (crush of physis).",
        "hashtags": ["#MedicoHelp", "#MBBS", "#NEETPG", "#Orthopedics", "#SalterHarris"],
    },
    {
        "title": "Bone Tumors: Osteosarcoma vs Ewing's Sarcoma — MCQ",
        "subject": Subject.orthopedics,
        "content_format": ContentFormat.mcq,
        "poster_text": "Bone Tumors MCQ — Osteosarcoma or Ewing's? Crack the X-Ray Clue",
        "caption": "BONE TUMORS — OSTEOSARCOMA vs EWING'S SARCOMA\n\nOSTEOSARCOMA:\n• Age: 10–20 years (2nd peak >60 in Paget's)\n• Site: Metaphysis of long bones; distal femur > proximal tibia > proximal humerus\n• X-ray: Sunburst pattern, Codman's triangle (periosteal elevation)\n• Histology: Malignant osteoid-producing cells\n• Treatment: Neoadjuvant chemotherapy + limb-salvage surgery\n• Markers: ALP elevated\n\nEWING'S SARCOMA:\n• Age: 5–15 years (younger than osteosarcoma)\n• Site: Diaphysis of long bones; also flat bones (pelvis, ribs, scapula)\n• X-ray: Onion-peel periosteal reaction\n• Histology: Small round blue cells; PAS positive\n• Translocation: t(11;22) — EWS-FLI1 fusion\n• Treatment: Chemotherapy + radiation (radiosensitive) ± surgery\n• May mimic osteomyelitis (fever, raised ESR, WBC)\n\nOTHER HIGH-YIELD TUMORS:\n• Giant Cell Tumor: Epiphysis, soap-bubble appearance, age 20–40\n• Osteochondroma: Most common benign bone tumor\n• Chondrosarcoma: Age >40, pelvis/proximal femur",
        "question": "A 12-year-old boy presents with 3 weeks of pain, swelling, and low-grade fever in his left thigh. Examination reveals a warm, tender swelling over the mid-shaft of the femur. His ESR is 85 mm/hr and WBC is 11,200/µL. X-ray shows a permeative lytic lesion in the diaphysis with an 'onion-peel' periosteal reaction. Biopsy reveals sheets of small round blue cells that are PAS-positive. Which of the following is the most likely diagnosis?",
        "options": [
            "A. Osteosarcoma",
            "B. Ewing's sarcoma",
            "C. Osteomyelitis",
            "D. Giant cell tumor",
        ],
        "correct_answer": "B. Ewing's sarcoma",
        "explanation": "The clinical picture is classic for Ewing's sarcoma: a child (5–15 years), diaphyseal location in a long bone, onion-peel periosteal reaction on X-ray, and histology showing small round blue cells (PAS-positive due to glycogen content). The fever and elevated inflammatory markers can mimic osteomyelitis — a common exam trap. Osteosarcoma typically affects the metaphysis, produces osteoid, and shows a sunburst pattern with Codman's triangle. Giant cell tumor occurs at the epiphysis in adults (20–40 years) with a soap-bubble appearance. Ewing's sarcoma carries the translocation t(11;22) creating the EWS-FLI1 fusion product. It is radiosensitive, and treatment involves multiagent chemotherapy with radiation and/or surgery.",
        "high_yield_takeaway": "Ewing's sarcoma: diaphysis, onion-peel, small round blue cells, t(11;22), mimics osteomyelitis. Osteosarcoma: metaphysis, sunburst, Codman's triangle, ALP elevated.",
        "hashtags": ["#MedicoHelp", "#MBBS", "#NEETPG", "#Orthopedics", "#BoneTumors"],
    },
    {
        "title": "Osteoarthritis vs Rheumatoid Arthritis — Complete Comparison",
        "subject": Subject.orthopedics,
        "content_format": ContentFormat.concise_notes,
        "poster_text": "OA vs RA — The Ultimate NEET-PG Comparison Table",
        "caption": "OSTEOARTHRITIS vs RHEUMATOID ARTHRITIS — CONCISE NOTES\n\nSECTION 1: PATHOGENESIS\n• OA: Degenerative, non-inflammatory. Articular cartilage breakdown → subchondral bone changes → osteophyte formation. Cytokines: IL-1β, TNF-α locally.\n• RA: Autoimmune, inflammatory. Synovial proliferation (pannus) → cartilage and bone erosion. Anti-CCP (most specific), RF positive.\n\nSECTION 2: EPIDEMIOLOGY\n• OA: Age >50, female predominance, obesity/trauma risk. Most common joint disease worldwide.\n• RA: Age 30–50, female:male = 3:1, HLA-DR4 association.\n\nSECTION 3: JOINTS INVOLVED\n• OA: DIP joints (Heberden's nodes), PIP joints (Bouchard's nodes), CMC of thumb, hip, knee, spine\n• RA: MCP + PIP joints (spares DIP), wrist, knee, C1-C2 (atlanto-axial subluxation)\n• Key: OA spares MCP; RA spares DIP\n\nSECTION 4: CLINICAL FEATURES\n• OA: Pain worsened by use, relieved by rest. Morning stiffness <30 min. No systemic features.\n• RA: Morning stiffness >1 hour. Systemic: fever, fatigue, weight loss. Symmetrical involvement.\n• RA deformities: Swan neck, Boutonniere, Z-deformity of thumb, ulnar deviation at MCP\n\nSECTION 5: INVESTIGATIONS\n• OA X-ray: LOSS — Loss of joint space, Osteophytes, Subchondral sclerosis, Subchondral cysts\n• RA X-ray: Juxta-articular osteopenia → erosions → joint space narrowing → ankylosis\n• Labs: OA — normal ESR/CRP; RA — elevated ESR, CRP, RF (70–80%), Anti-CCP (95% specific)\n\nSECTION 6: MANAGEMENT\n• OA: Weight loss, physiotherapy, NSAIDs, intra-articular steroids, joint replacement\n• RA: DMARDs (Methotrexate first-line), Hydroxychloroquine, Sulfasalazine; Biologics (anti-TNF) for refractory",
        "high_yield_takeaway": "OA: DIP/PIP, Heberden's/Bouchard's nodes, stiffness <30 min, X-ray LOSS. RA: MCP/PIP, spares DIP, stiffness >1 hr, anti-CCP most specific, Methotrexate first-line.",
        "hashtags": ["#MedicoHelp", "#MBBS", "#NEETPG", "#Orthopedics", "#Arthritis"],
    },
    {
        "title": "Supracondylar Fracture Complications — PYQ Pattern",
        "subject": Subject.orthopedics,
        "content_format": ContentFormat.pyq_concept,
        "poster_text": "Supracondylar Fracture — Every Complication NEET-PG Has Ever Asked",
        "caption": "SUPRACONDYLAR FRACTURE — PYQ PATTERN ANALYSIS\n\nThis is one of the HIGHEST-YIELD orthopedics topics. Appears in almost every NEET-PG, INI-CET, and AIIMS exam. Master every angle.\n\nBASIC FACTS (frequently tested):\n• Most common fracture around elbow in children (5–10 years)\n• Type: Gartland classification (I, II, III) — Type III = complete displacement\n• Mechanism: FOOSH (Fall On Outstretched Hand) → hyperextension\n• Posteromedial displacement → Anterior interosseous nerve (AIN) injury\n• Posterolateral displacement → Radial nerve / PIN injury\n\nCOMPLICATION → EXAM QUESTION PATTERN:\n\n1. Vascular injury → Brachial artery (most common)\n   PYQ: \"Child with supracondylar fracture, cold pulseless hand\" → Brachial artery injury\n\n2. Nerve injury → Anterior Interosseous Nerve (most common nerve)\n   PYQ: \"Cannot pinch — OK sign test positive\" → AIN palsy (no motor loss; weakness of FPL + FDP of index)\n   Note: Radial nerve if posterolateral; Median nerve overall most common in older texts\n\n3. Volkmann's Ischemic Contracture → missed compartment syndrome\n   PYQ: \"Late presentation, flexion deformity of wrist and fingers, intrinsic plus hand\"\n   Stages: Ischemia → Infarction → Fibrosis → Contracture\n\n4. Cubitus Varus (Gunstock deformity) → most common late complication\n   PYQ: \"Child 6 months post-fracture, elbow looks abnormal\" → Cubitus varus (cosmetic, not functional)\n   Cause: Malunion (not AVN, not growth arrest of medial condyle)\n\n5. Myositis Ossificans → heterotopic ossification after repeated manipulation\n   PYQ: \"Do NOT massage the fracture site\" → to prevent myositis ossificans\n\n6. Cubitus Valgus → lateral condyle fracture (not supracondylar) → tardy ulnar nerve palsy\n\nMANAGEMENT PYQ:\n• Gartland I → Above-elbow cast\n• Gartland II → Closed reduction + cast OR percutaneous K-wires\n• Gartland III + vascular compromise → Emergency reduction + K-wire fixation",
        "high_yield_takeaway": "Most common nerve: AIN (OK sign). Most common vascular: brachial artery. Most common late complication: cubitus varus (gunstock deformity). Volkmann's = missed compartment syndrome.",
        "hashtags": ["#MedicoHelp", "#MBBS", "#NEETPG", "#Orthopedics", "#SupracondylarFracture"],
    },
]
